services:
  fakestrava:
    build: ./FakeStrava
    container_name: fakestrava
    ports:
      - "5000:80"
    depends_on:
      - ocr-service

  ocr-service:
    build: ./ocr-service
    container_name: ocr-service
    ports:
      - "8000:8000"
